(function(){
'use strict';
var $=function(id){return document.getElementById(id)};
var E={side:$('side'),chatList:$('chatList'),messages:$('messages'),status:$('status'),history:$('historyBtn'),newBtn:$('newBtn'),newSide:$('newSide'),attach:$('attachBtn'),fileInput:$('fileInput'),attachments:$('attachments'),input:$('input'),send:$('sendBtn'),image:$('imageBtn'),web:$('webBtn'),md:$('mdBtn'),txt:$('txtBtn'),json:$('jsonBtn'),searchbar:$('searchbar'),searchInput:$('searchInput'),searchBtn:$('searchBtn'),toast:$('toast')};
var STORE='omnichat_v10';var chats=[];var activeId=null;var files=[];var busy=false;var timer;
function uid(){return 'c_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function newChat(){return{id:uid(),title:'New chat',messages:[],updated:Date.now()}}
function load(){try{var a=JSON.parse(localStorage.getItem(STORE)||'null');if(Array.isArray(a)&&a.length){chats=a;activeId=a[0].id;return}}catch(e){} var legacy=null;try{legacy=JSON.parse(localStorage.getItem('omnichat_chats')||'null')}catch(e){} chats=Array.isArray(legacy)&&legacy.length?legacy:[newChat()];activeId=chats[0].id;save()}
function save(){try{localStorage.setItem(STORE,JSON.stringify(chats))}catch(e){}}
function active(){return chats.find(function(c){return c.id===activeId})||chats[0]}
function toast(s){E.toast.textContent=s;E.toast.style.display='block';clearTimeout(timer);timer=setTimeout(function(){E.toast.style.display='none'},3200)}
function status(s){E.status.textContent=s}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function md(s){var x=esc(s);x=x.replace(/```([\w+-]*)\n([\s\S]*?)```/g,function(_,lang,code){return '<pre><code>'+code.replace(/\n$/,'')+'</code></pre>'});x=x.replace(/`([^`]+)`/g,'<code>$1</code>');x=x.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>');x=x.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>');return x.replace(/\n/g,'<br>')}
function render(){E.chatList.innerHTML='';chats.forEach(function(c){var r=document.createElement('div');r.className='chat-row';var b=document.createElement('button');b.className='chat-open'+(c.id===activeId?' active':'');b.textContent=c.title||'New chat';b.onclick=function(){activeId=c.id;render();save()};var d=document.createElement('button');d.className='chat-del';d.textContent='×';d.onclick=function(ev){ev.stopPropagation();chats=chats.filter(function(x){return x.id!==c.id});if(!chats.length)chats=[newChat()];if(!chats.some(function(x){return x.id===activeId}))activeId=chats[0].id;save();render()};r.appendChild(b);r.appendChild(d);E.chatList.appendChild(r)});E.messages.innerHTML='';var c=active();if(!c.messages.length){var q=document.createElement('div');q.className='empty';q.innerHTML='<h1>OmniChat</h1><p>Chat, code, analyze files, search the web and generate images.</p>';var qs=[['Weird fact','Tell me a weird but true fact.'],['Code','Write a small Python program that explains recursion.'],['Explain','Explain a difficult concept simply.']];var wrap=document.createElement('div');wrap.className='quick';qs.forEach(function(p){var b=document.createElement('button');b.textContent=p[0];b.onclick=function(){E.input.value=p[1];E.input.focus()};wrap.appendChild(b)});q.appendChild(wrap);E.messages.appendChild(q)}else c.messages.forEach(message);E.messages.scrollTop=E.messages.scrollHeight;renderFiles()}
function message(m){var d=document.createElement('div');d.className='msg '+(m.role==='user'?'user':'assistant');if(m.kind==='image'){d.textContent=m.prompt||'Generated image';var im=document.createElement('img');im.src=m.dataUrl;im.alt=m.prompt||'Generated image';d.appendChild(im);var a=document.createElement('div');a.className='actions';var b=document.createElement('button');b.textContent='↓ Download image';b.onclick=function(){downloadUrl(m.dataUrl,'omnichat-image.jpg')};a.appendChild(b);d.appendChild(a)}else if(m.kind==='file'){var card=document.createElement('div');card.className='file';card.innerHTML='<strong>📄 '+esc(m.filename)+'</strong>';var a=document.createElement('div');a.className='actions';var b=document.createElement('button');b.textContent='↓ Download';b.onclick=function(){download(m.data,m.mime,m.filename)};a.appendChild(b);card.appendChild(a);d.appendChild(card)}else{d.innerHTML=md(m.content||'');if(m.role==='assistant'){var a=document.createElement('div');a.className='actions';[['MD','md'],['TXT','txt'],['PDF','pdf'],['DOCX','docx']].forEach(function(p){var b=document.createElement('button');b.textContent='↓ '+p[0];b.onclick=function(){exportText(m.content,p[1],'omnichat-response')};a.appendChild(b)});d.appendChild(a)}}E.messages.appendChild(d)}
function renderFiles(){E.attachments.innerHTML='';files.forEach(function(f,i){var b=document.createElement('button');b.className='chip';b.textContent=f.name+' ×';b.onclick=function(){files.splice(i,1);renderFiles()};E.attachments.appendChild(b)})}
function download(blob,name){var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function downloadUrl(url,name){var a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove()}
function textOnly(s){return String(s||'').replace(/```[\s\S]*?\n|```/g,'').replace(/[#*_>`]/g,'')}
function exportText(text,ext,prefix){if(ext==='md')return download(new Blob([text],{type:'text/markdown'}),prefix+'.md');if(ext==='txt')return download(new Blob([textOnly(text)],{type:'text/plain'}),prefix+'.txt');if(ext==='pdf')return makePdf(textOnly(text),prefix+'.pdf');if(ext==='docx')return makeDocx(textOnly(text),prefix+'.docx')}
function makePdf(text,name){var lines=String(text).split('\n'),out='%PDF-1.4\n',objs=[];var pages=[];var pageLines=[];for(var i=0;i<lines.length;i++){var l=lines[i]||' ';if(l.length>95){while(l.length>95){pageLines.push(l.slice(0,95));l=l.slice(95)}}pageLines.push(l)}for(var p=0;p<pageLines.length;p+=45)pages.push(pageLines.slice(p,p+45));if(!pages.length)pages=[['']];var offsets=[0];function obj(s){offsets.push(out.length);out+=(objs.length+1)+' 0 obj\n'+s+'\nendobj\n';objs.push(s)}var font=objs.length+1;obj('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');var pageIds=[];pages.forEach(function(pg){var stream='BT /F1 10 Tf 50 790 Td 14 TL ';pg.forEach(function(l){stream+='('+l.replace(/([\\()])/g,'\\$1').replace(/[^\x20-\x7E]/g,'?')+') Tj T* '});stream+='ET';var sid=objs.length+1;obj('<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream');var pid=objs.length+1;obj('<< /Type /Page /Parent PAGES /MediaBox [0 0 595 842] /Resources << /Font << /F1 '+font+' 0 R >> >> /Contents '+sid+' 0 R >>');pageIds.push(pid)});var kids=pageIds.map(function(x){return x+' 0 R'}).join(' ');var pagesId=objs.length+1;obj('<< /Type /Pages /Kids ['+kids+'] /Count '+pageIds.length+' >>');var catalogId=objs.length+1;obj('<< /Type /Catalog /Pages '+pagesId+' 0 R >>');out=out.replaceAll('PAGES',pagesId+' 0 R');var xref=out.length;out+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(var j=1;j<=objs.length;j++)out+=String(offsets[j]).padStart(10,'0')+' 00000 n \n';out+='trailer\n<< /Size '+(objs.length+1)+' /Root '+catalogId+' 0 R >>\nstartxref\n'+xref+'\n%%EOF';download(new Blob([out],{type:'application/pdf'}),name)}
function crc32(buf){var t=crc32.table||(crc32.table=new Uint32Array(256));if(!t[1]){for(var n=0;n<256;n++){var c=n;for(var k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);t[n]=c>>>0}}var c=0xffffffff;for(var i=0;i<buf.length;i++)c=t[(c^buf[i])&255]^(c>>>8);return (c^0xffffffff)>>>0}
function u16(n){return new Uint8Array([n&255,n>>>8&255])}function u32(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255])}function cat(){var a=[].slice.call(arguments),n=a.reduce(function(s,x){return s+x.length},0),o=new Uint8Array(n),p=0;a.forEach(function(x){o.set(x,p);p+=x.length});return o}
function zipStore(files){var parts=[],central=[],offset=0;files.forEach(function(f){var name=new TextEncoder().encode(f.name),data=new TextEncoder().encode(f.data),crc=crc32(data);var h=cat(u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data);parts.push(h);var c=cat(u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name);central.push(c);offset+=h.length});var centLen=central.reduce(function(s,x){return s+x.length},0);var eocd=cat(u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(centLen),u32(offset),u16(0));return cat.apply(null,parts.concat(central,[eocd]))}
function xml(s){return esc(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function makeDocx(text,name){var paras=String(text).split('\n').map(function(l){return '<w:p><w:r><w:t xml:space="preserve">'+xml(l||' ')+'</w:t></w:r></w:p>'}).join('');var doc='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paras+'<w:sectPr/></w:body></w:document>';var ct='<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>';var rel='<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>';var wr='<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>';var z=zipStore([{name:'[Content_Types].xml',data:ct},{name:'_rels/.rels',data:rel},{name:'word/document.xml',data:doc},{name:'word/_rels/document.xml.rels',data:wr}]);download(new Blob([z],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),name)}
async function readFile(f){var fd=new FormData();fd.append('file',f,f.name);var r=await fetch('/api/convert',{method:'POST',body:fd});var d=await r.json();if(!r.ok)throw Error(d.error||'Could not read '+f.name);return d}
function target(s){s=String(s).toLowerCase();if(/\b(convert|save|turn|export)\b[\s\S]{0,80}\b(pdf)\b/.test(s))return'pdf';if(/\b(convert|save|turn|export)\b[\s\S]{0,80}\b(docx?)\b/.test(s))return'docx';return null}
async function send(){if(busy)return;var text=E.input.value.trim();if(!text&&!files.length)return;busy=true;E.send.disabled=true;try{var t=target(text);if(t&&files.length){var fs=files.slice();files=[];renderFiles();for(var i=0;i<fs.length;i++){status('Converting '+fs[i].name+'…');var d=await readFile(fs[i]);var name=fs[i].name.replace(/\.[^.]+$/,'')+'.'+t;if(t==='pdf')makePdf(textOnly(d.markdown),name);else makeDocx(textOnly(d.markdown),name);active().messages.push({role:'assistant',kind:'file',filename:name,data: t==='pdf'?'':'',mime:t==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});}save();render();toast('Download started.');return}var fs2=files.slice();files=[];renderFiles();var converted=[];for(var j=0;j<fs2.length;j++){status('Reading '+fs2[j].name+'…');converted.push(await readFile(fs2[j]))}var content=fs2.length?(text||'Analyze the attached file(s).')+'\n\nATTACHED FILE CONTENT:\n'+converted.map(function(x){return'--- '+x.name+' ---\n'+x.markdown}).join('\n\n'):text;var c=active();c.messages.push({role:'user',content:content});if(c.messages.length===1)c.title=(text||fs2[0]?.name||'New chat').slice(0,45);save();render();status('Working…');var r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:c.messages.slice(-40)})});var d=await r.json();if(!r.ok)throw Error(d.error||'Chat failed');c.messages.push({role:'assistant',content:d.answer});c.updated=Date.now();save();render()}catch(e){toast(e.message||'Request failed')}finally{busy=false;E.send.disabled=false;status('Ready')}}
async function image(){if(busy)return;var p=E.input.value.trim();if(!p)return toast('Write an image prompt first.');busy=true;E.image.disabled=true;status('Generating image…');try{var r=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p})});var d=await r.json();if(!r.ok)throw Error(d.error||'Image failed');active().messages.push({role:'assistant',kind:'image',prompt:p,dataUrl:d.dataUrl});E.input.value='';save();render()}catch(e){toast(e.message)}finally{busy=false;E.image.disabled=false;status('Ready')}}
async function webSearch(){var q=E.input.value.trim()||prompt('Web search query:');if(!q)return;busy=true;E.web.disabled=true;status('Searching the web…');try{var r=await fetch('/api/web-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q})});var d=await r.json();if(!r.ok)throw Error(d.error||'Search failed');var c=active();var text='Web search results for: '+q+'\n\n'+d.results.map(function(x,i){return(i+1)+'. '+x.title+'\n'+x.url+'\n'+x.snippet}).join('\n\n');c.messages.push({role:'user',content:'Search the web for: '+q});c.messages.push({role:'assistant',content:text});save();render()}catch(e){toast(e.message)}finally{busy=false;E.web.disabled=false;status('Ready')}}
function exportChat(ext){var c=active();if(!c.messages.length)return toast('Nothing to export.');var text=c.messages.map(function(m){return(m.role==='user'?'USER:\n':'ASSISTANT:\n')+(m.content||('[Generated '+m.kind+']'))}).join('\n\n');exportText(text,ext,(c.title||'omnichat'))}
E.send.onclick=send;E.input.onkeydown=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};E.attach.onclick=function(){E.fileInput.click()};E.fileInput.onchange=function(e){files=files.concat(Array.from(e.target.files||[]));renderFiles();E.fileInput.value=''};E.image.onclick=image;E.web.onclick=webSearch;E.newBtn.onclick=function(){chats.unshift(newChat());activeId=chats[0].id;save();render()};E.newSide.onclick=E.newBtn.onclick;E.history.onclick=function(){if(innerWidth<800)E.side.style.display=E.side.style.display==='flex'?'none':'flex'};E.md.onclick=function(){exportChat('md')};E.txt.onclick=function(){exportChat('txt')};E.json.onclick=function(){var c=active();download(new Blob([JSON.stringify(c,null,2)],{type:'application/json'}),(c.title||'omnichat')+'.json')};load();render();
})();
